services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: satellite_pass_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    env_file:
      - .env.docker
    depends_on:
      - db
    