# Generated by Django 6.0.4 on 2026-05-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pass',
            options={'verbose_name_plural': 'Passes'},
        ),
        migrations.RemoveField(
            model_name='location',
            name='altitude',
        ),
        migrations.RemoveField(
            model_name='pass',
            name='max_elevation',
        ),
        migrations.AddField(
            model_name='location',
            name='altitude_m',
            field=models.FloatField(default=0, verbose_name='Altitude (m)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pass',
            name='max_elevation_deg',
            field=models.FloatField(default=0, verbose_name='Max elevation (°)'),
            preserve_default=False,
        ),
    ]
