# Generated by Django 6.0.4 on 2026-05-21 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_pass_options_remove_location_altitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pass',
            options={'ordering': ['datetime'], 'verbose_name_plural': 'Passes'},
        ),
        migrations.AlterModelOptions(
            name='satellite',
            options={'ordering': ['name']},
        ),
    ]
